# Generated by Django 4.2.4 on 2023-09-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0058_alter_output_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.FloatField(default=0.0, verbose_name='Объем структуры, USDT')),
                ('percentage', models.FloatField(default=10.0, verbose_name='Процент депозита от объема структуры')),
                ('status', models.BooleanField(default=False, verbose_name='Подтверждение включения программы')),
                ('date_start', models.DateField(blank=True, help_text='Если дата уже существует, её нельзя редактировать', null=True, verbose_name='Дата старта программы')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата отключения программы')),
                ('deposit', models.FloatField(default=0.0, verbose_name='Активный депозит')),
                ('balance', models.FloatField(default=0.0, verbose_name='Баланс (сумма доступная к выводу)')),
                ('profit', models.FloatField(default=0.0, verbose_name='Доход за прошедшую неделю')),
                ('tg_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.j2muser', verbose_name='Пользователь ID')),
            ],
            options={
                'verbose_name': '[Промо] Карточка пользователя',
                'verbose_name_plural': '[Промо] Пользователи',
            },
        ),
    ]
