# Generated by Django 4.2.4 on 2023-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='date_start',
            field=models.DateField(blank=True, help_text='После внесения даты редактировать ее будет невозможно!', null=True, verbose_name='Дата старта программы'),
        ),
    ]
