# Generated by Django 4.2.1 on 2023-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='J2MUser',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram Id')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username')),
                ('tg_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('language', models.CharField(choices=[('RU', 'Русский'), ('EN', 'English')], max_length=2, verbose_name='Language')),
            ],
        ),
    ]
