# Generated by Django 4.2.1 on 2023-05-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='withdrawal',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Reserved balance for withdrawal'),
        ),
    ]
