# Generated by Django 4.2.1 on 2023-05-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_balance_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(choices=[('IN', 'Пополнение'), ('OUT', 'Вывод')], max_length=3, verbose_name='Status transaction')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('amount', models.BigIntegerField(verbose_name='Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.BooleanField(default=False, verbose_name='Transaction confirmed')),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.j2muser', verbose_name='User ID')),
            ],
        ),
    ]
