# Generated by Django 4.2.1 on 2023-05-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_balancehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_1_referrals', to='app.j2muser', verbose_name='Line 1')),
                ('line_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_2_referrals', to='app.j2muser', verbose_name='Line 2')),
                ('line_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_3_referrals', to='app.j2muser', verbose_name='Line 3')),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='app.j2muser', verbose_name='User ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='referal',
            constraint=models.UniqueConstraint(fields=('tg_id', 'line_1'), name='unique_tg_id_line_1'),
        ),
        migrations.AddConstraint(
            model_name='referal',
            constraint=models.UniqueConstraint(fields=('tg_id', 'line_2'), name='unique_tg_id_line_2'),
        ),
        migrations.AddConstraint(
            model_name='referal',
            constraint=models.UniqueConstraint(fields=('tg_id', 'line_3'), name='unique_tg_id_line_3'),
        ),
    ]
