# Generated by Django 4.2.1 on 2023-05-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_referal_referal_unique_tg_id_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='line_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_1_referrals', to='app.j2muser', verbose_name='Line 1'),
        ),
        migrations.AlterField(
            model_name='referal',
            name='line_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_2_referrals', to='app.j2muser', verbose_name='Line 2'),
        ),
        migrations.AlterField(
            model_name='referal',
            name='line_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_3_referrals', to='app.j2muser', verbose_name='Line 3'),
        ),
    ]
