# Generated by Django 4.2.1 on 2023-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_balance_options_alter_balancehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='referral_balance',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Реферальный баланс'),
        ),
    ]
