# Generated by Django 4.2.1 on 2023-06-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_balance_referral_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='j2muser',
            name='language',
            field=models.CharField(choices=[('RU', 'Русский'), ('EN', 'English')], max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='j2muser',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='j2muser',
            name='tg_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_approve', models.BooleanField(default=False, verbose_name='Подтвердил ли документы')),
                ('сontract', models.TextField(blank=True, null=True, verbose_name='Подписанный контракт')),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.j2muser', unique=True, verbose_name='Пользователь')),
            ],
        ),
    ]
