# Generated by Django 4.2.1 on 2023-06-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_j2muser_language_alter_j2muser_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Контракт', 'verbose_name_plural': 'Документы пользователей'},
        ),
        migrations.AddField(
            model_name='j2muser',
            name='alias',
            field=models.TextField(blank=True, null=True, verbose_name='Alias'),
        ),
        migrations.CreateModel(
            name='Binance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(verbose_name='API Key')),
                ('secret_key', models.TextField(verbose_name='API Secret key')),
                ('tg_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.j2muser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Binance API',
                'verbose_name_plural': 'Подключение к Binance',
            },
        ),
    ]
