# Generated by Django 4.2.1 on 2023-06-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_documents_options_j2muser_alias_binance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='сontract',
            new_name='contract',
        ),
    ]
