# Generated by Django 4.2.1 on 2023-06-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_сontract_documents_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='Сумма пополнения')),
                ('invoiceId', models.TextField(verbose_name='Уникальный номер транзакции')),
                ('date', models.DateTimeField(verbose_name='Время начала транзакции')),
                ('status', models.TextField(null=True, verbose_name='Статус транзакции')),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.j2muser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Thedex API',
                'verbose_name_plural': 'Транзакции Thedex',
            },
        ),
    ]
