# Generated by Django 4.2.1 on 2023-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_thedex_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='approve_contract',
            field=models.BooleanField(default=False, verbose_name='Пользовательский контракт заполнен верно?'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='documents_approve',
            field=models.BooleanField(default=False, verbose_name='Пользователь подтвердил соглашения с J2M'),
        ),
    ]
