# Generated by Django 4.2.1 on 2023-06-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_documents_approve_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='contract',
            field=models.URLField(blank=True, null=True, verbose_name='Подписанный контракт'),
        ),
    ]
