# Generated by Django 4.2.1 on 2023-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_documents_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='contract',
            field=models.TextField(blank=True, null=True, verbose_name='Подписанный контракт'),
        ),
    ]
