# Generated by Django 4.2.1 on 2023-06-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_documents_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='j2muser',
            name='wallet',
            field=models.TextField(blank=True, null=True, verbose_name='Кошелек для вывода'),
        ),
        migrations.AlterField(
            model_name='j2muser',
            name='alias',
            field=models.TextField(blank=True, null=True, verbose_name='Почта Binance'),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='Сумма к выводу')),
                ('date', models.DateTimeField(verbose_name='Дата создания заявки')),
                ('wallet', models.TextField(verbose_name='Кошелек для вывода TRC-20')),
                ('approve', models.BooleanField(default=False, verbose_name='Подтверждаете отправку средств на указанный кошелек?')),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.j2muser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на вывод',
                'verbose_name_plural': 'Заявки на вывод средств',
            },
        ),
    ]
