# Generated by Django 4.2.1 on 2023-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_balance_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='settings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Настройки перевода с баланса на активный депозит (%)'),
        ),
    ]
