# Generated by Django 4.2.1 on 2023-06-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_nft'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала транзакции'),
        ),
        migrations.AddField(
            model_name='nft',
            name='invoiceId',
            field=models.TextField(blank=True, null=True, verbose_name='Уникальный номер транзакции'),
        ),
        migrations.AddField(
            model_name='nft',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='Статус транзакции'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес кошелька с NFT'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='private_key',
            field=models.TextField(blank=True, null=True, verbose_name='Приватный ключ'),
        ),
    ]
