# Generated by Django 4.2.1 on 2023-06-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_nft_date_nft_invoiceid_nft_status_alter_nft_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='tg_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.j2muser', verbose_name='Пользователь'),
        ),
    ]
