# Generated by Django 4.2.1 on 2023-06-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_sendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='hash',
            field=models.TextField(blank=True, null=True, verbose_name='Хэш транзакции'),
        ),
        migrations.AlterField(
            model_name='balancehistory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Хэш транзакции'),
        ),
    ]
