# Generated by Django 4.2.1 on 2023-06-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_output_hash_alter_balancehistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='j2muser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Личная почта'),
        ),
    ]
