# Generated by Django 4.2.1 on 2023-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_sendmessageforgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessageforgroup',
            name='group',
            field=models.CharField(choices=[('DAO', 'Владельцы NFT'), ('DU', 'Коллективный аккаунт'), ('CA', 'Личный аккаунт'), ('ALL', 'Все пользователи'), ('EMP', 'Лохи без смарт-контракта')], max_length=3, verbose_name='Выберите группу пользователей'),
        ),
    ]
