# Generated by Django 4.2.1 on 2023-07-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_balancej2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancej2m',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='balancej2m',
            name='date',
        ),
        migrations.AddField(
            model_name='balancej2m',
            name='balance_monday',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Баланс на понедельник (USDT)'),
        ),
        migrations.AddField(
            model_name='balancej2m',
            name='balance_sunday',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Баланс на воскресенье (USDT)'),
        ),
        migrations.AddField(
            model_name='balancej2m',
            name='date_monday',
            field=models.DateField(blank=True, null=True, verbose_name='Понедельник (Дата)'),
        ),
        migrations.AddField(
            model_name='balancej2m',
            name='date_sunday',
            field=models.DateField(blank=True, null=True, verbose_name='Воскресенье (Дата)'),
        ),
        migrations.AddField(
            model_name='balancej2m',
            name='profit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Доход (USDT)'),
        ),
    ]
