# Generated by Django 4.2.1 on 2023-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_balancej2m_balance_remove_balancej2m_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancej2m',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='Доход (%)'),
        ),
    ]
