# Generated by Django 4.2.1 on 2023-07-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_everydaybalance_alter_balancej2m_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(verbose_name='API Key')),
                ('secret_key', models.TextField(verbose_name='Secret Key')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание кошелька')),
            ],
            options={
                'verbose_name': 'Binance J2M',
                'verbose_name_plural': 'Binance API J2M',
            },
        ),
    ]
