# Generated by Django 4.2.1 on 2023-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_apikeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='everydaybalance',
            name='balance',
        ),
        migrations.AddField(
            model_name='everydaybalance',
            name='balance_busd',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Баланс (BUSD)'),
        ),
        migrations.AddField(
            model_name='everydaybalance',
            name='balance_usdt',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Баланс (USDT)'),
        ),
        migrations.AddField(
            model_name='everydaybalance',
            name='total',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Общий баланс (без учета коэфициентов)'),
        ),
    ]
