# Generated by Django 4.2.1 on 2023-07-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_everydaybalance_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancej2m',
            old_name='balance_monday',
            new_name='balance_monday_usdt',
        ),
        migrations.RenameField(
            model_name='balancej2m',
            old_name='balance_sunday',
            new_name='balance_sunday_usdt',
        ),
        migrations.AddField(
            model_name='balancej2m',
            name='balance_monday_busd',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Баланс на понедельник (BUSD)'),
        ),
        migrations.AddField(
            model_name='balancej2m',
            name='balance_sunday_busd',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Баланс на воскресенье (BUSD)'),
        ),
        migrations.AlterField(
            model_name='balancej2m',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='Доход % - BUSD + USDT '),
        ),
    ]
