# Generated by Django 4.2.1 on 2023-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_balance_balance_alter_balance_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thedex',
            name='invoiceId',
            field=models.TextField(unique=True, verbose_name='Уникальный номер транзакции'),
        ),
        migrations.AlterUniqueTogether(
            name='balancehistory',
            unique_together={('tg_id', 'description')},
        ),
    ]
