# Generated by Django 4.2.1 on 2023-07-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_thedex_invoiceid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balancehistory',
            unique_together=set(),
        ),
    ]
