# Generated by Django 4.2.1 on 2023-07-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_balancehistory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balancehistory',
            unique_together={('tg_id', 'description')},
        ),
    ]
