# Generated by Django 4.2.1 on 2023-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_balance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binance',
            options={'verbose_name': 'Binance API', 'verbose_name_plural': 'ЛИЧНЫЙ АККАУНТ - Балансы пользователей (Binance)'},
        ),
        migrations.AddField(
            model_name='binance',
            name='balance_binance',
            field=models.FloatField(blank=True, null=True, verbose_name='Баланс на Binance'),
        ),
        migrations.AddField(
            model_name='binance',
            name='balance_j2m',
            field=models.FloatField(blank=True, null=True, verbose_name='Баланс J2M'),
        ),
        migrations.AddField(
            model_name='binance',
            name='deposit',
            field=models.FloatField(blank=True, null=True, verbose_name='Активный депозит'),
        ),
    ]
