# Generated by Django 4.2.1 on 2023-07-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_binance_options_binance_balance_binance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='contract',
        ),
        migrations.AddField(
            model_name='documents',
            name='it_product',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подтвердил ли пользователь Приложение No 1 к Условиям применения IT продукта'),
        ),
    ]
