# Generated by Django 4.2.4 on 2023-08-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoposting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('post_time', models.DateTimeField(verbose_name='Время поста')),
                ('accept', models.BooleanField(default=False, verbose_name='Подтверждено?')),
            ],
            options={
                'verbose_name': 'Автопостинг',
                'verbose_name_plural': 'Автопостинг',
            },
        ),
    ]
