# Generated by Django 4.2.4 on 2023-08-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoposting', '0003_autoposting_callback_name_autoposting_callback_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoposting',
            name='send',
            field=models.BooleanField(default=False, help_text='Это поле заполняется автоматически после отправки', verbose_name='Отправлено?'),
        ),
        migrations.AlterField(
            model_name='autoposting',
            name='text',
            field=models.TextField(help_text="HTML-теги: <b>Жирность</b> (&lt;b&gt;Жирность&lt;/b&gt;), <em>Курсив</em> (&lt;em&gt;Курсив&lt;/em&gt;), <a href=''>Ссылка</a> (&lt;a href='https://www.example.com'&gt;Ссылка&lt;/a&gt;)", verbose_name='Текст поста'),
        ),
    ]
