# Generated by Django 4.2.4 on 2023-09-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoposting', '0009_alter_autoposting_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoposting',
            name='post_time',
            field=models.DateTimeField(help_text='Московское время: 21.09.2023 16:56', verbose_name='Время поста'),
        ),
    ]
