# Generated by Django 4.2.1 on 2023-07-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0048_alter_documents_documents_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_collective', models.FloatField(default=0, verbose_name='Баланс коллективный ДЕМО')),
                ('deposit_collective', models.FloatField(default=0, verbose_name='Активный депозит коллективный ДЕМО')),
                ('api_key', models.TextField(verbose_name='API Key ДЕМО')),
                ('secret_key', models.TextField(verbose_name='API Secret key ДЕМО')),
                ('balance_binance', models.FloatField(blank=True, null=True, verbose_name='Баланс на Binance ДЕМО')),
                ('balance_j2m', models.FloatField(blank=True, null=True, verbose_name='Баланс J2M ДЕМО')),
                ('balance_personal', models.FloatField(default=0, verbose_name='Баланс коллективный ДЕМО')),
                ('deposit_personal', models.FloatField(blank=True, null=True, verbose_name='Активный депозит ДЕМО')),
                ('tg_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.j2muser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': '[Демо] Баланс пользователя',
                'verbose_name_plural': '[Демо] Балансы пользователя',
            },
        ),
        migrations.CreateModel(
            name='DemoBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(choices=[('IN', 'Пополнение'), ('OUT', 'Вывод')], max_length=3, verbose_name='Статус транзакции')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('amount', models.BigIntegerField(verbose_name='Сумма')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Хэш транзакции')),
                ('status', models.BooleanField(default=False, verbose_name='Подтверждение транзакции')),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.j2muser', verbose_name='Пользователь ID')),
            ],
            options={
                'verbose_name': '[Демо] История баланса',
                'verbose_name_plural': '[Демо] История пополнения и вывода',
            },
        ),
    ]
