# Generated by Django 4.2.1 on 2023-07-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demouser',
            name='balance_j2m',
        ),
        migrations.AlterField(
            model_name='demouser',
            name='balance_personal',
            field=models.FloatField(blank=True, null=True, verbose_name='Баланс J2M ДЕМО'),
        ),
    ]
