# Generated by Django 4.2.1 on 2023-07-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_remove_demouser_balance_j2m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demouser',
            name='api_key',
            field=models.TextField(blank=True, null=True, verbose_name='API Key ДЕМО'),
        ),
        migrations.AlterField(
            model_name='demouser',
            name='secret_key',
            field=models.TextField(blank=True, verbose_name='API Secret key ДЕМО'),
        ),
    ]
