# Generated by Django 4.2.1 on 2023-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_demouser_api_key_alter_demouser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demouser',
            name='secret_key',
            field=models.TextField(blank=True, null=True, verbose_name='API Secret key ДЕМО'),
        ),
    ]
