# Generated by Django 4.2.4 on 2023-08-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_balancehistory_transaction_type'),
        ('demo', '0004_alter_demouser_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoStabPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, verbose_name='Баланс')),
                ('deposit', models.FloatField(default=0, verbose_name='Активный депозит')),
                ('withdrawal', models.FloatField(blank=True, null=True, verbose_name='Зарезервированная сумма для вывода')),
                ('hold', models.IntegerField(blank=True, null=True, verbose_name='Количество дней холда')),
                ('weekly_profit', models.FloatField(blank=True, null=True, verbose_name='Доход за торговую неделю')),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.j2muser', verbose_name='Пользователь ID')),
            ],
            options={
                'verbose_name': '[Демо] Баланс пользователя',
                'verbose_name_plural': '[Демо] СТАБИЛИЗАЦИОННЫЙ ПУЛ - Балансы пользователей',
            },
        ),
    ]
