# Generated by Django 4.2.4 on 2023-08-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_demostabpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='demobalancehistory',
            name='transaction_type',
            field=models.TextField(blank=True, null=True, verbose_name='Тип аккаунта'),
        ),
    ]
