# Generated by Django 4.2.4 on 2023-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата расчета недельной проторговки')),
                ('collective_profit', models.FloatField(default=0.0, verbose_name='Доход коллективных аккаунтов, %')),
                ('stabpool_profit', models.FloatField(default=0.0, verbose_name='Доход стабилизационного пула, %')),
                ('is_withdrawal', models.BooleanField(default=False, verbose_name='Выводная неделя?')),
            ],
            options={
                'verbose_name': 'Процент дохода пользователей',
                'verbose_name_plural': 'Расчетный модуль',
            },
        ),
    ]
